### ISSUE TITLE
npt files are not available once created from an hdf5 

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#171]
this is not really clear, but the error message is this one

Now fill in the ring number. Ring number starts at 0, like point-groups.
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyFAI-calib.py", line 59, in <module>
    c.gui_peakPicker()
  File "C:\Python27\lib\site-packages\pyFAI\calibration.py", line 1142, in gui_peakPicker
    self.set_data(self.peakPicker.finish(self.pointfile))
  File "C:\Python27\lib\site-packages\pyFAI\peak_picker.py", line 497, in finish
    self.points.save(filename)
  File "C:\Python27\lib\site-packages\pyFAI\peak_picker.py", line 778, in save
    with open(filename, "w") as f:
IOError: [Errno 2] No such file or directory: 'hdf5://Al_484.nxs:/scan_486/DIFFABS/MAR345/data.npt'

Indeed this file name is not valid.

**Comment by kif** [comment]
now it works
