### ISSUE TITLE
Nvidia Quadro K4000 error when using xrpd_OpenCL

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#173]
Hello

runfile('C:/Users/reguer/.nexpy/plugins/carto/treatment.py', wdir='C:/Users/reguer/.nexpy/plugins/carto')
WARNING:pyFAI.detectors:enforcing pixel size 2 for a detector Mar345
WARNING:pyFAI.detectors:enforcing pixel size 2 for a detector Mar345
Z:\com-diffabs\2014\Run4B\20140507\NXSdata\Al_484.nxs
Traceback (most recent call last):

  File "<ipython-input-29-0bafee0dea9b>", line 1, in <module>
    runfile('C:/Users/reguer/.nexpy/plugins/carto/treatment.py', wdir='C:/Users/reguer/.nexpy/plugins/carto')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 66, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/reguer/.nexpy/plugins/carto/treatment.py", line 75, in <module>
    traitement(PONI, FILES, OUTPUT)

  File "C:/Users/reguer/.nexpy/plugins/carto/treatment.py", line 70, in traitement
    for i, dataframe in enumerate(integrate(poni, files)):

  File "C:/Users/reguer/.nexpy/plugins/carto/treatment.py", line 48, in integrate
    tth, intensity = ai.xrpd_OpenCL(dataframe.image, N, mask=mask)

  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 926, in xrpd_OpenCL
    if integr.configure():

  File "C:\Python27\lib\site-packages\pyFAI\ocl_azim.py", line 342, in configure
    self._compile_kernels(kernel)

  File "C:\Python27\lib\site-packages\pyFAI\ocl_azim.py", line 245, in _compile_kernels
    self._cl_program.build(options=compile_options)

  File "C:\Python27\lib\site-packages\pyopencl\__init__.py", line 209, in build
    options=options, source=self._source)

  File "C:\Python27\lib\site-packages\pyopencl\__init__.py", line 249, in _build_and_catch_errors
    raise err

RuntimeError: clBuildProgram failed: build program failure - 

Build on <pyopencl.Device 'Quadro K4000' on 'NVIDIA CUDA' at 0x13a99f18>:

<kernel>:346:22: error: invalid operands to binary expression ('__attribute__((address_space(16776963))) float' and 'int')
          if(inrange && cbin < BINS){
             ~~~~~~~ ^  ~~~~~~~~~~~

(options: -D BLOCK_SIZE=128  -D BINS=2000 -D NN=5290000 -D ENABLE_FP64 -I c:\python27\lib\site-packages\pyopencl\cl)
(source saved as c:\users\reguer\appdata\local\temp\tmpmkghmb.cl)

**Comment by kif** [comment]
On Fri, 13 Feb 2015 00:54:30 -0800
picca <notifications@github.com> wrote:

> Build on <pyopencl.Device 'Quadro K4000' on 'NVIDIA CUDA' at 0x13a99f18>:
> 
> <kernel>:346:22: error: invalid operands to binary expression ('__attribute__((address_space(16776963))) float' and 'int')
>           if(inrange && cbin < BINS){

I had a look at the kernel: there is an obfuscation of the use of float.


-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>
