### ISSUE TITLE
Detector error when saving poni file with an HDF detector

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#239]
voici l'erreur et le merge.poni

matpc:boudet2/02-02-827/analysis % pyFAI-calib -c LaB6 -D d7_flat.h5 -f 
flat.edf -e 10 ../raw/15Nov26D7_0004.edf
INFO:root:Enter, port=54321.
INFO:root:Enter.
FixedParameters(['wavelength'])
INFO:pyFAI.utils:Reading ../raw/15Nov26D7_0004.edf
INFO:pyFAI.utils:Wrote merged.edf
INFO:pyFAI.massif:Image size is (960, 560)
INFO:pyFAI.massif:Binning size is [1, 1]
INFO:pyFAI.massif:Labeling found 4857 massifs.
INFO:pyFAI.massif:Labeling found 4857 massifs.
INFO:root:Please select rings on the diffraction image. In parenthesis, 
some modified shortcuts for single button mouse (Apple):
  * Right-click (click+n):         try an auto find for a ring
  * Right-click + Ctrl (click+b):  create new group with one point
  * Right-click + Shift (click+v): add one point to current group
  * Right-click + m (click+m):     find more points for current group
  * Center-click or (click+d):     erase current group
  * Center-click + 1 or (click+1): erase closest point from current group
Please press enter when you are happy with your selection

Now fill in the ring number. Ring number starts at 0, like point-groups.
Point group # a (1 points)	 ( 467.2, 592.1) 	 [default=1] Ring#
Point group # b (3 points)	 ( 454.0, 545.9) 	 [default=1] Ring#
Point group # c (1 points)	 ( 429.8, 463.0) 	 [default=1] Ring#
Point group # d (2 points)	 ( 430.0, 476.0) 	 [default=1] Ring#
Point group # e (2 points)	 ( 426.0, 391.0) 	 [default=1] Ring#
Point group # f (1 points)	 ( 427.0, 408.0) 	 [default=1] Ring#
Point group # g (4 points)	 ( 431.0, 335.0) 	 [default=1] Ring#
Point group # h (1 points)	 ( 435.0, 310.0) 	 [default=1] Ring#
Point group # i (2 points)	 ( 443.0, 270.0) 	 [default=1] Ring#
Point group # j (3 points)	 ( 470.1, 210.9) 	 [default=1] Ring#
Point group # k (1 points)	 ( 485.0, 161.0) 	 [default=1] Ring#
Point group # l (2 points)	 ( 489.0, 153.9) 	 [default=1] Ring#
Point group # m (2 points)	 ( 496.0, 634.0) 	 [default=1] Ring#
Point group # n (1 points)	 ( 463.0, 835.0) 	 [default=2] Ring#
Point group # o (1 points)	 ( 450.0, 816.0) 	 [default=2] Ring#
Point group # p (1 points)	 ( 409.0, 754.0) 	 [default=2] Ring#
Point group # q (1 points)	 ( 404.0, 745.2) 	 [default=2] Ring#
Point group # r (5 points)	 ( 352.1, 670.9) 	 [default=2] Ring#
Point group # s (1 points)	 ( 327.1, 602.0) 	 [default=2] Ring#
Point group # t (1 points)	 ( 311.9, 565.0) 	 [default=2] Ring#
Point group # u (1 points)	 ( 315.0, 576.1) 	 [default=2] Ring#
Point group # v (1 points)	 ( 305.9, 541.0) 	 [default=2] Ring#
Point group # w (1 points)	 ( 298.0, 504.0) 	 [default=2] Ring#
Point group # x (1 points)	 ( 284.9, 426.0) 	 [default=2] Ring#
Point group # y (1 points)	 ( 284.1, 406.2) 	 [default=2] Ring#
Point group # z (1 points)	 ( 284.1, 416.8) 	 [default=2] Ring#
Point group #aa (1 points)	 ( 284.0, 386.8) 	 [default=2] Ring#
Point group #ab (2 points)	 ( 286.9, 342.9) 	 [default=2] Ring#
Point group #ac (7 points)	 ( 292.0, 304.8) 	 [default=2] Ring#
Point group #ad (4 points)	 ( 300.9, 253.1) 	 [default=2] Ring#
Point group #ae (1 points)	 ( 314.0, 229.0) 	 [default=2] Ring#
Point group #af (1 points)	 ( 332.0, 149.0) 	 [default=2] Ring#
Point group #ag (1 points)	 ( 368.0,  97.2) 	 [default=2] Ring#
Point group #ah (1 points)	 ( 257.0, 953.2) 	 [default=4] Ring#
Point group #ai (1 points)	 ( 196.8, 842.0) 	 [default=4] Ring#
Point group #aj (1 points)	 ( 172.1, 828.9) 	 [default=4] Ring#
Point group #ak (1 points)	 ( 166.9, 818.2) 	 [default=4] Ring#
Point group #al (7 points)	 ( 145.0, 755.1) 	 [default=4] Ring#
Point group #am (4 points)	 ( 116.9, 712.1) 	 [default=4] Ring#
Point group #an (2 points)	 ( 103.1, 675.0) 	 [default=4] Ring#
Point group #ao (1 points)	 (  91.0, 630.0) 	 [default=4] Ring#
Point group #ap (2 points)	 (  89.0, 619.0) 	 [default=4] Ring#
Point group #aq (1 points)	 (  71.0, 554.0) 	 [default=4] Ring#
Point group #ar (2 points)	 (  67.0, 529.9) 	 [default=4] Ring#
Point group #as (3 points)	 (  64.0, 505.8) 	 [default=4] Ring#
Point group #at (1 points)	 (  57.0, 468.0) 	 [default=4] Ring#
Point group #au (3 points)	 (  55.8, 447.7) 	 [default=4] Ring#
Point group #av (1 points)	 (  55.8, 423.0) 	 [default=4] Ring#
Point group #aw (2 points)	 (  54.0, 407.0) 	 [default=4] Ring#
Point group #ax (2 points)	 (  54.0, 380.0) 	 [default=4] Ring#
Point group #ay (4 points)	 (  55.2, 350.0) 	 [default=4] Ring#
Point group #az (7 points)	 (  56.2, 317.9) 	 [default=4] Ring#
Point group #ba (2 points)	 (  64.0, 253.0) 	 [default=4] Ring#
Point group #bb (1 points)	 (  74.8, 209.9) 	 [default=4] Ring#
Point group #bc (2 points)	 (  85.8, 139.0) 	 [default=4] Ring#
Point group #bd (1 points)	 ( 101.8, 111.0) 	 [default=4] Ring#
Point group #be (1 points)	 ( 117.0,  66.0) 	 [default=4] Ring#
Point group #bf (1 points)	 ( 124.8,  45.0) 	 [default=4] Ring#
Point group #bg (2 points)	 ( 106.3, 100.2) 	 [default=4] Ring#

Optimization terminated successfully.    (Exit mode 0)
             Current function value: 4.10848500807e-05
             Iterations: 196
             Function evaluations: 1654
             Gradient evaluations: 196
INFO:pyFAI.geometryRefinement:Constrained Least square 0.0662449103208 
--> 3.57259565919e-07  
INFO:pyFAI.geometryRefinement:maxdelta on rot1: 0.0 --> -0.524149812596
Optimization terminated successfully.    (Exit mode 0)
             Current function value: 4.1084043163e-05
             Iterations: 65
             Function evaluations: 566
             Gradient evaluations: 65
INFO:pyFAI.geometryRefinement:Constrained Least square 0.0338922499774 
--> 3.57252549243e-07  
INFO:pyFAI.geometryRefinement:maxdelta on rot1: 0.0 --> -0.523853201798
ERROR:pyFAI.detectors:Detector nexusdetector is unknown !, please check 
if the filename exists or select one from ['imxpads70', 'rayonix_mx225', 
'eiger1m', 'imxpads10', 'mar_345', 'titan', 'rayonixlx225', 'pilatus2m', 
'agilent_titan', 'rayonixmx225hs', 'fairchildcondor486:90', 
'rayonix_mx425hs', 'rayonix_sx85hs', 'rayonixmx170', 'mar165', 
'perkinelmer', 'titan2kx2k', 'rayonix', 'xpads540flat', 'mar133', 
'rayonixmx300hs', 'rayonix133', 'condor', 'fairchild_condor_486:90', 
'eiger16m', 'rayonix_mx170', 'rayonixsx165', 'xpad_flat', 
'agilenttitan', 'oxd_titan', 'perkin_elmer', 'rayonixlx255', 
'dexela_2923', 'pilatus6m', 'titan_2k_x_2k', 'aca1300', 'oxdtitan', 
'pilatus1m', 'xpad_s540_flat', 'mar3450', 'rayonixlx170', 'basler', 
'eiger4m', 'rayonix_lx170', 'imxpad_s10', 'rayonix_sx200', 
'rayonixsx85hs', 'rayonixmx225', 'pilatus300k', 'rayonix_lx225', 
'perkin_detector', 'pilatus200k', 'imxpads140', 'detector', 
'rayonixmx300', 'rayonix_sx165', 'imxpad_s140', 'pilatus300kw', 
'imxpad_s70', 'fairchild', 'rayonixsx200', 'rayonix_mx225hs', 
'rayonix_sx30hs', 'rayonix_mx340hs', 'eiger9m', 'perkin', 
'rayonixsx30hs', 'rayonixmx340hs', 'mar345', 'perkindetector', 
'rayonixmx425hs', 'rayonixmx325', 'rayonix_mx300', 'pilatus100k', 
'rayonix_mx325', 'rayonix_mx300hs', 'dexela2923']
Traceback (most recent call last):
   File "/usr/bin/pyFAI-calib", line 59, in <module>
     c.gui_peakPicker()
   File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 
1345, in gui_peakPicker
     self.set_data(self.peakPicker.finish(self.pointfile))
   File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 
1165, in set_data
     self.refine()
   File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 
1407, in refine
     self.geoRef.load(paramfile)
   File "/usr/lib/python2.7/dist-packages/pyFAI/geometry.py", line 954, 
in load
     self.detector = detectors.detector_factory(data["detector"])
   File "/usr/lib/python2.7/dist-packages/pyFAI/detectors.py", line 121, 
in factory
     raise RuntimeError(msg)
RuntimeError: Detector nexusdetector is unknown !, please check if the 
filename exists or select one from ['imxpads70', 'rayonix_mx225', 
'eiger1m', 'imxpads10', 'mar_345', 'titan', 'rayonixlx225', 'pilatus2m', 
'agilent_titan', 'rayonixmx225hs', 'fairchildcondor486:90', 
'rayonix_mx425hs', 'rayonix_sx85hs', 'rayonixmx170', 'mar165', 
'perkinelmer', 'titan2kx2k', 'rayonix', 'xpads540flat', 'mar133', 
'rayonixmx300hs', 'rayonix133', 'condor', 'fairchild_condor_486:90', 
'eiger16m', 'rayonix_mx170', 'rayonixsx165', 'xpad_flat', 
'agilenttitan', 'oxd_titan', 'perkin_elmer', 'rayonixlx255', 
'dexela_2923', 'pilatus6m', 'titan_2k_x_2k', 'aca1300', 'oxdtitan', 
'pilatus1m', 'xpad_s540_flat', 'mar3450', 'rayonixlx170', 'basler', 
'eiger4m', 'rayonix_lx170', 'imxpad_s10', 'rayonix_sx200', 
'rayonixsx85hs', 'rayonixmx225', 'pilatus300k', 'rayonix_lx225', 
'perkin_detector', 'pilatus200k', 'imxpads140', 'detector', 
'rayonixmx300', 'rayonix_sx165', 'imxpad_s140', 'pilatus300kw', 
'imxpad_s70', 'fairchild', 'rayonixsx200', 'rayonix_mx225hs', 
'rayonix_sx30hs', 'rayonix_mx340hs', 'eiger9m', 'perkin', 
'rayonixsx30hs', 'rayonixmx340hs', 'mar345', 'perkindetector', 
'rayonixmx425hs', 'rayonixmx325', 'rayonix_mx300', 'pilatus100k', 
'rayonix_mx325', 'rayonix_mx300hs', 'dexela2923']

nils

-- 
--------------------------------------------
Nils BLANC
Néel institute (MCMF) - CNRS Grenoble
25 rue des martyrs
BP 166
38042 Grenoble CEDEX 9
- - - - - - - - - - - - - - - - - - - - - -
ESRF-The European Synchrotron
BM02-CRG D2am
71, Avenue des Martyrs
CS40220
38043 Grenoble CEDEX 9
- - - - - - - - - - - - - - - - - - - - - -
Phone at ESRF: BM02 +33 4 76 88 21 88
--------------------------------------------

[merged-2.poni  text/plain (1114 bytes)]

**Comment by kif** [comment]
corresponding detector file
# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis 
# Calibration done at Thu Nov 26 14:23:50 2015
Detector: NexusDetector
PixelSize1: 0.000130000000354
PixelSize2: 0.000130000000354
Distance: 0.202423776679
Poni1: 0.0724906408783
Poni2: 0.0388538578386
Rot1: -0.524281611241
Rot2: -0.0360536903111
Rot3: -2.94439048955e-09
SplineFile: None
Wavelength: 1.2398419292e-10
# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis 
# Calibration done at Thu Nov 26 14:24:57 2015
Detector: NexusDetector
PixelSize1: 0.000130000000354
PixelSize2: 0.000130000000354
Distance: 0.202423776679
Poni1: 0.0724906408783
Poni2: 0.0388538578386
Rot1: -0.524281611241
Rot2: -0.0360536903111
Rot3: -2.94439048955e-09
SplineFile: None
Wavelength: 1.2398419292e-10
# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis 
# Calibration done at Thu Nov 26 14:25:18 2015
Detector: NexusDetector
PixelSize1: 0.000130000000354
PixelSize2: 0.000130000000354
Distance: 0.202423776679
Poni1: 0.0724906408783
Poni2: 0.0388538578386
Rot1: -0.524281611241
Rot2: -0.0360536903111
Rot3: 1.57
SplineFile: None
Wavelength: 1.2398419292e-10

**Comment by kif** [comment]
works (example:WOS)
