### ISSUE TITLE
API change in FabIO

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#258]
Dear Jerome,

I’ve recently started using PyFAI to do azimuthal integrations of 2D diffraction images.

Firstly, I should note that I had a couple of issues with my installation on OSX El Capitan. I followed your notes on the github trouble ticket, but there were some extra steps required:
- I had to use an older version of scipy (0.12, not 0.17)
- I then had to update numpy to 1.10.4
Now both pyFAI-calib and -integrate will both load OK and I can make e.g. a poni file without issue.

I can also do a radial integration without any azimuthal points specified, however when I specify the number of points I get the following error:
INFO:pyFAI.integrate_widget:Parameters for integration:
dummy: None
npt_azim: 18
error_model: None
delta_dummy: None
npt_rad: 512
safe: False
filename: None
method: splitbbox
correctSolidAngle: False
polarization_factor: None
unit: 2th_deg
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pyFAI/integrate_widget.py", line 414, in proceed
    res = self.ai.integrate2d(**kwarg)
  File "/Library/Python/2.7/site-packages/pyFAI/azimuthalIntegrator.py", line 3132, in integrate2d
    normalization_factor=normalization_factor)
  File "/Library/Python/2.7/site-packages/pyFAI/azimuthalIntegrator.py", line 3384, in save2D
    header_keys=header_keys)
TypeError: __init__() got an unexpected keyword argument 'header_keys'

The file is an .EDF from the Pilatus2M on ID31. Do you have any idea what the problem might be?

Thanks,

Hugh

**Comment by kif** [comment]
the bug comes from the de-synchronization of FabIO and PyFAI
