### ISSUE TITLE
Bad mask gives surprising error message

### ISSUE THREAD

**Issue by jonwright** [kif/pyFAI#271]
It took a while to debug a script which was making a mask automatically when this error message showed up. The origin seems to be having all pixels masked: this messes with the generation of the radial ranges. It can be reproduced with any poni/data file, just mask the entire image:

```
import pyFAI, fabio, numpy
ai = pyFAI.load("ceo2_hf_flood_0050.poni")
im=fabio.open("ceo2_hf_flood_0050.edf").data
x,y=ai.integrate1d(im, 1000)
# OK
x,y=ai.integrate1d(im, 1000,mask=numpy.ones(im.shape))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 2286, in integrate1d
    mask_checksum=mask_crc, unit=unit)
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 1063, in setup_LUT
    unit=unit)
  File "src/splitBBoxLUT.pyx", line 151, in src.splitBBoxLUT.HistoBBox1d.__init__ (src/splitBBoxLUT.c:3938)
  File "src/splitBBoxLUT.pyx", line 289, in src.splitBBoxLUT.HistoBBox1d.calc_lut (src/splitBBoxLUT.c:5694)
  File "stringsource", line 147, in View.MemoryView.array.__cinit__ (src/splitBBoxLUT.c:22748)
ValueError: Invalid shape in axis 1: 0.
```

**Comment by kif** [comment]
Indeed the LUT generation algorithm crashes while the CSR return an array of I with the dummy value but with a stupid radial range (always the same point).
I will address this
